### ISSUE TITLE
Bug: findItemAttribute returns 0 itemAttributes

### ISSUE THREAD

**Issue by YuRiTan** [Ginns/inventorious#18]
Not able to resolve this yet. Hope you can Rosco!

I discussed a new implementation with Jeroen. You can contact me if you solved the bug and we are able to go on.

**Comment by TheDudiful** [comment]
When running the app, everything works fine, but when running the tests it breaks

**Comment by TheDudiful** [comment]
The problem is in the fact that the Cable category has two CONNECTORS attributes, when creating a new Cable item, however, it only uses the second CONNECTORS attribute instead of both. Hence, if you use get(0) from the findCategoryAttribute results, it won't have any associated items. get(1) does. I don't get why the program behaves like this, but it does. A simple fix would be only giving Cable one CONNECTORS attribute and manually adding the second one in Cable items, but I don't feel like that is the correct way, as cables should always have two connectors. We'll look at this again tomorrow morning.
